export const WORDS: string[] = [
  // ── Animaux ──────────────────────────────────────────────────────────────────
  'chat', 'chien', 'cheval', 'lion', 'tigre', 'éléphant', 'girafe', 'singe',
  'dauphin', 'requin', 'baleine', 'aigle', 'perroquet', 'crocodile', 'kangourou',
  'pingouin', 'panda', 'koala', 'zèbre', 'renard', 'loup', 'ours', 'lapin',
  'vache', 'cochon', 'mouton', 'poule', 'coq', 'canard', 'oie', 'dinde',
  'grenouille', 'serpent', 'lézard', 'tortue', 'araignée', 'papillon', 'abeille',
  'fourmi', 'libellule', 'coccinelle', 'escargot', 'crabe', 'homard', 'pieuvre',
  'méduse', 'hippocampe', 'saumon', 'thon', 'sardine', 'piranha', 'anguille',
  'corbeau', 'hibou', 'cigogne', 'flamant', 'paon', 'toucan', 'colibri',
  'chauve-souris', 'hérisson', 'taupe', 'écureuil', 'castor', 'loutre',
  'rhinocéros', 'hippopotame', 'guépard', 'léopard', 'jaguar', 'puma',
  'gorille', 'chimpanzé', 'cerf', 'sanglier', 'chevreuil', 'biche',
  'chameau', 'dromadaire', 'lama', 'alpaga', 'bison', 'buffle', 'yak',
  'autruche', 'émeu', 'manchot', 'morse', 'phoque', 'otarie', 'narval',
  'faucon', 'buse', 'chouette', 'rouge-gorge', 'martin-pêcheur', 'héron',
  'moustique', 'sauterelle', 'grillon', 'luciole', 'ver de terre', 'limace',
  'scorpion', 'puce', 'pigeon', 'mouche', 'dinosaure', 'chihuahua', 'poisson-chat',
  'tarentule', 'cobra', 'python', 'anaconda', 'boa', 'caméléon', 'gecko',
  'hippopotame', 'wombat', 'tapir', 'tatou', 'fourmilier', 'pangolin',
  'belette', 'hermine', 'putois', 'blaireau', 'lynx', 'ocelot', 'serval',
  'mandrill', 'babouine', 'macaque', 'capucin', 'ouistiti', 'tamarin',
  'cigale', 'doryphore', 'hanneton', 'bourdon', 'guêpe', 'frelon',
  'calamar', 'crevette', 'langoustine', 'palourde', 'moule', 'huître',
  'hippocampe', 'raie', 'espadon', 'poisson-clown', 'mérou', 'murène',

  // ── Transports ────────────────────────────────────────────────────────────────
  'voiture', 'avion', 'bateau', 'vélo', 'train', 'fusée', 'hélicoptère',
  'moto', 'camion', 'bus', 'tramway', 'métro', 'sous-marin', 'montgolfière',
  'parachute', 'planeur', 'jet-ski', 'pirogue', 'kayak', 'canot', 'voilier',
  'ferry', 'porte-avions', 'tracteur', 'bulldozer', 'grue', 'excavatrice',
  'ambulance', 'taxi', 'limousine', 'caravane', 'camping-car',
  'scooter', 'trottinette', 'skateboard', 'rollers', 'char', 'tank', 'jeep',
  'carriole', 'diligence', 'calèche', 'chariot', 'brouette',
  'funiculaire', 'téléphérique', 'remontée mécanique', 'segway',
  'paquebot', 'péniche', 'galère', 'caravelle', 'jonque', 'catamaran',
  'deltaplane', 'ULM', 'biplan', 'concorde', 'navette spatiale',
  'tricycle', 'tandem', 'quad', 'side-car', 'remorque',

  // ── Objets quotidiens ─────────────────────────────────────────────────────────
  'téléphone', 'ordinateur', 'télévision', 'chapeau', 'lunettes', 'parapluie',
  'valise', 'horloge', 'bougie', 'clé', 'marteau', 'couteau', 'fourchette',
  'cuillère', 'assiette', 'tasse', 'bouteille', 'verre', 'casserole', 'poêle',
  'frigo', 'four', 'micro-ondes', 'grille-pain', 'cafetière', 'mixeur',
  'aspirateur', 'fer à repasser', 'sèche-cheveux', 'miroir',
  'savon', 'brosse à dents', 'rasoir', 'peigne', 'ciseau', 'colle',
  'stylo', 'crayon', 'règle', 'gomme', 'livre', 'enveloppe', 'timbre',
  'lampe', 'ampoule', 'montre', 'bague', 'collier', 'bracelet', 'ceinture', 'portefeuille',
  'sac à main', 'sac à dos', 'panier', 'boîte', 'cadenas', 'vase',
  'arrosoir', 'pelle', 'râteau', 'échelle', 'corde', 'ancre', 'boussole', 'jumelles', 'loupe',
  'thermomètre', 'balance', 'calendrier', 'drapeau', 'carte postale',
  'télécommande', 'réveil', 'baromètre', 'calculatrice', 'photocopieuse',
  'imprimante', 'scanner', 'clé USB', 'disque dur', 'souris', 'clavier',
  'tournevis', 'pince', 'scie', 'rabot', 'perceuse', 'clé à molette',
  'cric', 'extincteur', 'détecteur de fumée', 'trousse de secours',
  'poubelle', 'éponge', 'balai', 'serpillière', 'seau', 'porte-monnaie',
  'distributeur de billets', 'GPS', 'lecteur MP3', 'walkman', 'cassette VHS',
  'cabine téléphonique', 'prise de courant', 'interrupteur', 'bavoir',
  'biberon', 'couche', 'hochet', 'landau', 'poussette',
  'cartable', 'trousse', 'taille-crayon', 'agrafeuse', 'scotch',
  'porte-clés', 'briquet', 'allumette', 'cierge', 'bougie d\'anniversaire',
  'stéthoscope', 'seringue', 'béquille', 'fauteuil roulant', 'plâtre',
  'loupe', 'microscope', 'télescope', 'sextant', 'astrolabe',
  'éventail', 'ombrelle', 'canne', 'bâton de marche', 'lasso',
  'aimant', 'boussole', 'thermomètre', 'chronomètre', 'sablier',
  'abaque', 'règle à calcul', 'compas', 'équerre', 'rapporteur',
  'palette', 'pinceau', 'chevalet', 'cadre', 'toile',
  'fil à plomb', 'niveau', 'mètre ruban', 'équerre', 'trusquin',

  // ── Instruments de musique ────────────────────────────────────────────────────
  'guitare', 'piano', 'tambour', 'violon', 'trompette', 'flûte', 'saxophone',
  'accordéon', 'harpe', 'contrebasse', 'trombone', 'cor', 'tuba', 'clarinette',
  'hautbois', 'basson', 'orgue', 'xylophone', 'maracas', 'castagnettes', 'cymbales',
  'triangle', 'ukulélé', 'mandoline', 'banjo', 'sitar', 'djembé', 'bongos',
  'didgeridoo', 'cornemuse', 'sitar', 'kora', 'balafon', 'kalimba',
  'luth', 'clavecin', 'synthétiseur', 'boîte à musique', 'carillon',
  'vibraphone', 'glockenspiel', 'steel drum', 'tabla', 'pandeiro',
  'guimbarde', 'ocarina', 'tin whistle', 'shakuhachi', 'erhu',

  // ── Nourriture ────────────────────────────────────────────────────────────────
  'pizza', 'hamburger', 'sushi', 'croissant', 'gâteau', 'glace', 'banane',
  'pomme', 'fraise', 'ananas', 'cerise', 'pastèque', 'raisin', 'citron',
  'carotte', 'brocoli', 'tomate', 'poivron', 'champignon', 'oignon',
  'pain', 'baguette', 'beurre', 'fromage', 'yaourt', 'confiture',
  'pâtes', 'riz', 'soupe', 'salade', 'sandwich', 'tarte', 'crêpe', 'gaufre',
  'bonbon', 'chocolat', 'caramel', 'sucette', 'macaron', 'madeleine', 'brioche',
  'framboise', 'myrtille', 'kiwi', 'mangue', 'papaye', 'coco', 'avocat', 'figue',
  'prune', 'pêche', 'poire', 'melon', 'abricot', 'orange', 'pamplemousse',
  'poireau', 'haricot', 'petits pois', 'maïs', 'aubergine', 'courgette', 'radis',
  'navet', 'betterave', 'artichaut', 'asperge', 'chou-fleur', 'épinard', 'laitue',
  'poulet', 'saucisse', 'jambon', 'steak', 'oeuf', 'omelette', 'frites',
  'taco', 'burrito', 'paella', 'raclette', 'fondue', 'quiche', 'lasagne',
  'spaghetti', 'carbonara', 'risotto', 'couscous', 'tajine', 'ramen', 'pho',
  'moules-frites', 'bouillabaisse', 'cassoulet', 'pot-au-feu', 'blanquette',
  'boeuf bourguignon', 'ratatouille', 'gratin dauphinois', 'vichyssoise',
  'éclair', 'mille-feuille', 'paris-brest', 'saint-honoré', 'tarte tatin',
  'kouglof', 'financier', 'cannelé', 'calisson', 'nougat', 'praline',
  'chips', 'pop-corn', 'nuggets', 'hot-dog', 'bretzel', 'bagel',
  'courgette', 'patate douce', 'topinambour', 'panais', 'céleri', 'fenouil',
  'truffe', 'morille', 'cèpe', 'pleurote', 'girolle', 'chanterelle',
  'litchi', 'ramboutan', 'carambole', 'durian', 'grenade', 'kakis',
  'noix', 'amande', 'noisette', 'pistache', 'cajou', 'pécan', 'macadamia',
  'olive', 'câpre', 'cornichon', 'pickles', 'moutarde', 'ketchup', 'mayo',
  'café', 'thé', 'lait', 'bière', 'vin', 'champagne', 'cidre',
  'limonade', 'jus d\'orange', 'smoothie', 'milkshake', 'cocktail', 'sirop',

  // ── Lieux & bâtiments ─────────────────────────────────────────────────────────
  'plage', 'montagne', 'forêt', 'désert', 'île', 'château', 'palais',
  'phare', 'volcan', 'cascade', 'pyramide', 'igloo', 'cabane', 'grotte',
  'école', 'hôpital', 'église', 'mosquée', 'cathédrale', 'synagogue', 'pagode',
  'musée', 'cinéma', 'théâtre', 'bibliothèque', 'supermarché', 'boulangerie',
  'restaurant', 'hôtel', 'gare', 'aéroport', 'port', 'marina',
  'stade', 'piscine', 'gymnase', 'parc', 'zoo', 'cirque', 'fête foraine',
  'ferme', 'usine', 'banque', 'prison', 'tribunal', 'mairie',
  'tour Eiffel', 'Colisée', 'Statue de la Liberté', 'Big Ben', 'Stonehenge',
  'grande muraille de Chine', 'Taj Mahal', 'Acropole', 'Angkor Vat',
  'mont Rushmore', 'arc de Triomphe', 'Notre-Dame de Paris', 'Louvre',
  'casino', 'discothèque', 'karaoké', 'bowling', 'karting', 'laser game',
  'escape room', 'aquarium', 'planétarium', 'observatoire', 'laboratoire',
  'épicerie', 'marché', 'bazar', 'souk', 'foire', 'salon', 'congrès',
  'parking', 'autoroute', 'pont', 'tunnel', 'barrage', 'centrale électrique',
  'phare', 'fort', 'rempart', 'tour de guet', 'donjon', 'fossé',
  'ranch', 'haras', 'élevage', 'serre', 'jardin botanique', 'verger',
  'camping', 'caravaning', 'auberge', 'gîte', 'chalet', 'bungalow',
  'cabane dans les arbres', 'maison sur pilotis', 'igloo', 'tipi', 'yourte',
  'phare', 'brise-lames', 'jetée', 'quai', 'embarcadère', 'digue',

  // ── Nature & météo ────────────────────────────────────────────────────────────
  'soleil', 'lune', 'étoile', 'nuage', 'pluie', 'neige', 'tonnerre', 'arc-en-ciel',
  'vent', 'tornade', 'tsunami', 'avalanche', 'lave', 'tremblement de terre',
  'rivière', 'lac', 'océan', 'falaise', 'glacier', 'fjord', 'delta',
  'arbre', 'rose', 'tulipe', 'tournesol', 'cactus', 'bambou', 'séquoia',
  'fougère', 'algue', 'herbe', 'mousse', 'lichen', 'orchidée', 'magnolia',
  'cerisier en fleur', 'bonsaï', 'lierre', 'vigne', 'blé', 'lavande',
  'orage', 'brouillard', 'brume', 'grêle', 'verglas', 'givre', 'rosée',
  'aurore boréale', 'eclipse solaire', 'éclipse lunaire', 'comète', 'météorite',
  'désert de sel', 'oasis', 'dune', 'savane', 'toundra', 'taïga', 'mangrove',
  'récif corallien', 'marécage', 'tourbière', 'prairie', 'garrigue', 'maquis',
  'geyser', 'source thermale', 'lac de lave', 'stalactite', 'stalagmite',
  'île volcanique', 'atoll', 'lagon', 'détroit', 'cap', 'péninsule', 'isthme',
  'plaine', 'plateau', 'col', 'sommet', 'versant', 'ravin', 'canyon', 'gorge',

  // ── Actions & verbes ──────────────────────────────────────────────────────────
  'dormir', 'courir', 'nager', 'voler', 'danser', 'chanter', 'lire',
  'sourire', 'pleurer', 'rire', 'crier', 'sauter', 'tomber', 'grimper',
  'plonger', 'skier', 'surfer', 'escalader', 'peindre', 'sculpter',
  'cuisiner', 'rêver', 'méditer', 'conduire', 'pédaler', 'ramer',
  'attraper', 'lancer', 'frapper', 'construire', 'creuser', 'planter',
  'faire la vaisselle', 'passer l\'aspirateur', 'faire les courses',
  'accrocher un cadre', 'jeter les poubelles', 'manger des spaghettis',
  'faire une bataille de boules de neige', 'assembler un Lego',
  'se brosser les dents', 'se peigner', 'se raser', 'se maquiller', 'se doucher',
  'photographier', 'filmer', 'dessiner', 'écrire', 'imprimer',
  'téléphoner', 'regarder', 'écouter', 'sentir', 'goûter',
  'nourrir un animal', 'promener un chien', 'traire une vache',
  'vendanger', 'labourer', 'semer', 'récolter', 'irriguer',
  'nager le crawl', 'nager le papillon', 'nager le dos',
  'faire du yoga', 'faire des pompes', 'faire des abdos',
  'jongler', 'faire du vélo acrobatique', 'faire du BMX',
  'faire du funambulisme', 'faire du trapèze', 'faire du trampoline',
  'faire du vélo de montagne', 'descendre en rappel',
  'tirer à l\'arc', 'lancer le javelot', 'lancer le marteau',
  'pousser une voiture', 'tirer une corde', 'porter des sacs',
  'être en colère', 'être amoureux', 'être surpris', 'avoir peur',

  // ── Sports ────────────────────────────────────────────────────────────────────
  'football', 'basketball', 'tennis', 'natation', 'boxe', 'judo', 'karaté',
  'ski', 'snowboard', 'surf', 'escalade', 'cyclisme', 'athlétisme',
  'rugby', 'volleyball', 'badminton', 'golf', 'baseball', 'cricket', 'hockey',
  'bowling', 'billard', 'fléchettes', 'ping-pong', 'pétanque', 'escrime',
  'tir à l\'arc', 'équitation', 'plongée', 'parachutisme',
  'ski nautique', 'wakeboard', 'kite-surf', 'windsurf', 'stand-up paddle',
  'aviron', 'canoë-kayak', 'polo aquatique', 'water-polo',
  'triathlon', 'décathlon', 'pentathlon', 'biathlon',
  'luge', 'bobsleigh', 'curling', 'patinage artistique', 'patinage de vitesse',
  'ski de fond', 'ski alpin', 'ski de randonnée', 'ski de saut',
  'lutte', 'sumo', 'taekwondo', 'kung-fu', 'aïkido', 'capoeira',
  'CrossFit', 'musculation', 'haltérophilie', 'powerlifting',
  'course à pied', 'marathon', 'semi-marathon', 'sprint', 'haies',
  'saut en hauteur', 'saut en longueur', 'triple saut', 'saut à la perche',
  'lancer du poids', 'lancer du disque', 'lancer du javelot',
  'handball', 'futsal', 'pétanque', 'boules', 'croquet', 'polo',
  'pelote basque', 'bras de fer', 'jeux de quilles', 'frisbee ultimate',
  'padel', 'squash', 'racquetball', 'tennis de table', 'badminton',
  'jeux olympiques', 'coupe du monde', 'tour de France',

  // ── Professions ───────────────────────────────────────────────────────────────
  'médecin', 'pompier', 'policier', 'cuisinier', 'boulanger', 'professeur',
  'astronaute', 'pilote', 'soldat', 'roi', 'reine', 'chevalier',
  'magicien', 'clown', 'acrobate', 'chanteur', 'acteur', 'peintre',
  'architecte', 'informaticien', 'journaliste', 'photographe',
  'jardinier', 'vétérinaire', 'dentiste', 'infirmier', 'pharmacien',
  'avocat', 'juge', 'détective', 'espion', 'facteur',
  'plombier', 'électricien', 'maçon', 'menuisier',
  'chirurgien', 'cardiologue', 'pédiatre', 'psychiatre', 'radiologue',
  'kinésithérapeute', 'ostéopathe', 'acupuncteur', 'sage-femme',
  'astronome', 'physicien', 'chimiste', 'biologiste', 'géologue', 'paléontologue',
  'archéologue', 'anthropologue', 'sociologue', 'psychologue', 'économiste',
  'avocat', 'notaire', 'huissier', 'procureur', 'magistrat',
  'diplomate', 'ambassadeur', 'consul', 'sénateur', 'député', 'ministre',
  'sapeur-pompier', 'gendarme', 'douanier', 'garde-frontière', 'ranger',
  'guide de montagne', 'guide touristique', 'interprète', 'traducteur',
  'libraire', 'antiquaire', 'commissaire-priseur', 'galeriste', 'conservateur',
  'chef d\'orchestre', 'compositeur', 'arrangeur', 'producteur', 'DJ',
  'réalisateur', 'scénariste', 'monteur', 'perchman', 'caméraman',
  'mannequin', 'styliste', 'costumier', 'coiffeur', 'maquilleur',
  'sommelier', 'caviste', 'barista', 'pâtissier', 'chocolatier', 'fromager',
  'berger', 'vigneron', 'apiculteur', 'ostréiculteur', 'pêcheur',
  'bucheron', 'forestier', 'garde champêtre', 'géomètre', 'arpenteur',
  'plongeur professionnel', 'démineur', 'artificier', 'pyrotechnicien',
  'funambule', 'cracheur de feu', 'dompteur', 'dresseur', 'équilibriste',

  // ── Vêtements & accessoires ───────────────────────────────────────────────────
  'manteau', 'veste', 'pull', 'chemise', 'robe', 'jupe', 'pantalon', 'jean',
  'short', 'maillot de bain', 'pyjama', 'imperméable', 'combinaison',
  'chaussures', 'bottes', 'baskets', 'sandales', 'talons', 'chaussons',
  'chaussettes', 'collants', 'gants', 'écharpe', 'bonnet', 'béret', 'casque',
  'chapeau de cowboy', 'casquette', 'couronne', 'masque', 'cagoule',
  'kimono', 'sari', 'kilt', 'dirndl', 'djellaba', 'hanbok', 'qipao',
  'tutu', 'justaucorps', 'legging', 'cycliste', 'débardeur', 'bustier',
  'smokig', 'frac', 'redingote', 'gilet', 'blazer', 'trench', 'doudoune',
  'chapeau melon', 'chapeau haut-de-forme', 'sombrero', 'fez', 'turban', 'toque',
  'cravate', 'nœud papillon', 'pochette', 'broche', 'épaulettes',
  'lunettes de soleil', 'monocle', 'lorgnon', 'binocle',
  'sac banane', 'besace', 'cartable', 'mallette', 'attaché-case',
  'mitaines', 'moufles', 'cache-col', 'snood', 'cache-oreilles',
  'tablier', 'blouse', 'salopette', 'combinaison de travail', 'gilet de sauvetage',

  // ── Corps humain ──────────────────────────────────────────────────────────────
  'main', 'pied', 'oeil', 'nez', 'oreille', 'bouche', 'dent', 'langue',
  'cheveux', 'barbe', 'moustache', 'joue', 'front', 'menton', 'nuque',
  'bras', 'jambe', 'genou', 'coude', 'épaule', 'dos', 'ventre',
  'coeur', 'poumon', 'squelette', 'crâne', 'muscle', 'colonne vertébrale',
  'estomac', 'foie', 'rate', 'rein', 'pancréas', 'intestin', 'appendice',
  'veine', 'artère', 'capillaire', 'lymphe', 'plasma',
  'nerf', 'neurone', 'synapse', 'cerveau', 'cervelet', 'tronc cérébral',
  'rétine', 'pupille', 'iris', 'cristallin', 'cornée', 'paupière', 'cil',
  'tympan', 'cochlée', 'sinus', 'narine', 'glotte', 'larynx', 'trachée',
  'clavicule', 'sternum', 'côte', 'omoplate', 'bassin', 'fémur', 'tibia',
  'empreinte digitale', 'veine', 'tatouage', 'cicatrice', 'grain de beauté',
  'poil', 'ongle', 'cuticule', 'cou', 'gorge', 'pomme d\'Adam',

  // ── Maison & meubles ──────────────────────────────────────────────────────────
  'maison', 'appartement', 'villa', 'tente', 'tipi', 'yourte', 'igloo',
  'chaise', 'table', 'lit', 'canapé', 'fauteuil', 'bureau', 'armoire',
  'étagère', 'bibliothèque', 'porte', 'fenêtre', 'volet', 'portail',
  'escalier', 'balcon', 'terrasse', 'garage', 'cave', 'grenier', 'sous-sol',
  'cheminée', 'radiateur', 'ventilateur', 'rideau', 'tapis', 'piscine', 'jacuzzi',
  'baignoire', 'douche', 'lavabo', 'bidet', 'WC', 'robinet', 'bonde',
  'réfrigérateur', 'congélateur', 'lave-vaisselle', 'lave-linge', 'sèche-linge',
  'hotte aspirante', 'plaque de cuisson', 'plan de travail', 'évier',
  'canapé-lit', 'futon', 'hamac', 'pouf', 'banquette', 'méridienne',
  'guéridon', 'console', 'buffet', 'vitrine', 'desserte', 'bahut',
  'lustre', 'applique', 'lampadaire', 'lampe de chevet', 'spot',
  'tableau', 'affiche', 'miroir', 'horloge murale', 'papier peint',
  'parquet', 'carrelage', 'moquette', 'lino', 'béton ciré',
  'toiture', 'gouttière', 'cheminée', 'antenne', 'parabole', 'panneau solaire',
  'palissade', 'clôture', 'portail', 'boîte aux lettres', 'interphone',

  // ── Technologie & science ─────────────────────────────────────────────────────
  'robot', 'satellite', 'telescope', 'microscope', 'boussole',
  'drone', 'tablette', 'casque VR', 'manette', 'console de jeux',
  'panneau solaire', 'éolienne', 'centrale nucléaire',
  'imprimante 3D', 'scanner 3D', 'bras robotique', 'exosquelette',
  'intelligence artificielle', 'hologramme', 'réalité augmentée',
  'GPS', 'radar', 'sonar', 'LIDAR', 'capteur', 'capteur infrarouge',
  'transistor', 'diode', 'circuit intégré', 'micropuce', 'nano-capteur',
  'fusible', 'condensateur', 'résistance', 'transformateur',
  'laser', 'prisme', 'lentille', 'miroir concave', 'miroir convexe',
  'aimant', 'électroaimant', 'bobine', 'générateur', 'alternateur',
  'tube à essais', 'bécher', 'erlenmeyer', 'pipette', 'burette',
  'centrifugeuse', 'autoclave', 'étuve', 'réfractomètre',
  'corde à sauter', 'ressort', 'poulie', 'levier', 'engrenage',
  'serveur', 'routeur', 'switch', 'modem', 'firewall', 'câble Ethernet',
  'fibre optique', 'antenne Wi-Fi', 'Bluetooth', 'NFC', 'QR code',

  // ── Divertissement ────────────────────────────────────────────────────────────
  'cinéma', 'dessin animé', 'bande dessinée', 'manga', 'roman photo',
  'concert', 'cirque', 'jonglage', 'acrobatie', 'magie', 'prestidigitation',
  'jeu de société', 'échecs', 'dames', 'Monopoly', 'Scrabble', 'Risk',
  'puzzle', 'Rubik\'s cube', 'Sudoku', 'mots croisés', 'rébus',
  'poupée', 'nounours', 'Lego', 'yo-yo', 'toupie', 'bilboquet',
  'cerf-volant', 'bulles de savon', 'balle rebondissante', 'élastique',
  'feu d\'artifice', 'pétard', 'confettis', 'ballon de baudruche', 'cotillon',
  'anniversaire', 'mariage', 'Noël', 'Halloween', 'carnaval', 'mascarade', 'fête nationale',
  'rollercoaster', 'manège', 'grande roue', 'toboggan', 'balançoire', 'trampoline',
  'château gonflable', 'pêche aux canards', 'stand de tir', 'jeu de massacre',
  'karaoké', 'blind test', 'quiz', 'escape game', 'jeu de piste', 'chasse au trésor',
  'marionnette', 'théâtre de guignol', 'spectacle de rue', 'mime', 'pantomime',
  'origami', 'macramé', 'broderie', 'tricot', 'crochet', 'poterie', 'céramique',
  'aquarelle', 'pastels', 'fusain', 'gravure', 'linogravure', 'lithographie',
  'photographie', 'photo argentique', 'chambre noire', 'darkroom',

  // ── Mythologie & fantastique ──────────────────────────────────────────────────
  'dragon', 'vampire', 'zombie', 'fantôme', 'sorcière', 'loup-garou', 'licorne',
  'sirène', 'elfe', 'nain', 'ogre', 'géant', 'fée', 'lutin', 'gnome',
  'phénix', 'sphinx', 'minotaure', 'centaure', 'griffon', 'pégase', 'basilic',
  'Père Noël', 'ange', 'démon', 'momie', 'alien', 'extraterrestre',
  'cyclope', 'méduse', 'hydre', 'chimère', 'manticore', 'hippogriffe',
  'kirin', 'qilin', 'naga', 'kappa', 'tengu', 'oni', 'yokai', 'golem',
  'génie', 'djinn', 'ifrit', 'elfe de nuit', 'elfe des bois', 'dryade', 'naïade',
  'nymphe', 'satyres', 'faune', 'centaure', 'minotaure', 'labyrinthe',
  'sorcier', 'necromancien', 'paladin', 'barde', 'druide', 'chaman',
  'zombie apocalypse', 'invasion alien', 'robot tueur', 'intelligence artificielle rebelle',
  'arche de Noé', 'tour de Babel', 'Atlantide', 'El Dorado', 'Avalon', 'Valhalla',

  // ── Espace ────────────────────────────────────────────────────────────────────
  'planète', 'astéroïde', 'comète', 'trou noir', 'galaxie', 'constellation',
  'Soleil', 'Lune', 'Mars', 'Jupiter', 'Saturne', 'Venus', 'Mercure', 'Neptune', 'Uranus',
  'soucoupe volante', 'vaisseau spatial', 'navette spatiale', 'station spatiale',
  'rover', 'sonde spatiale', 'télescope spatial', 'anneau de Saturne',
  'supernova', 'nébuleuse', 'pulsar', 'quasar', 'matière noire', 'énergie sombre',
  'lune de Jupiter', 'astéroïde géant', 'ceinture de Kuiper',
  'Big Bang', 'expansion de l\'univers', 'horizon des événements',
  'vol habité', 'alunissage', 'décollage', 'rentrée atmosphérique',

  // ── Concepts & expressions ────────────────────────────────────────────────────
  'amour', 'paix', 'guerre', 'victoire', 'défaite', 'rêve', 'cauchemar',
  'liberté', 'justice', 'égalité', 'espoir', 'joie', 'tristesse',
  'magie', 'mystère', 'trésor', 'pirate', 'ninja', 'cowboy', 'viking',
  'temps', 'infini', 'hasard', 'destin', 'chance', 'malchance',
  'vérité', 'mensonge', 'secret', 'complot', 'rumeur', 'légende',
  'froid', 'chaud', 'calme', 'tempête', 'chaos', 'ordre', 'équilibre',
  'gravité', 'magnétisme', 'électricité', 'lumière', 'obscurité', 'ombre',
  'silence', 'bruit', 'musique', 'harmonie', 'dissonance', 'rythme',
  'vitesse', 'lenteur', 'force', 'faiblesse', 'courage', 'lâcheté', 'peur',
  'surprise', 'dégoût', 'honte', 'fierté', 'jalousie', 'envie', 'nostalgie',
  'solitude', 'amitié', 'famille', 'communauté', 'nation', 'humanité',
  'naissance', 'vie', 'vieillesse', 'mort', 'au-delà', 'réincarnation',
  'évolution', 'révolution', 'renaissance', 'décadence', 'apocalypse',
  'paradis', 'enfer', 'purgatoire', 'nirvana', 'karma', 'yin yang',
  'carte aux trésors', 'boîte de Pandore', 'cheval de Troie', 'épée de Damoclès',
  'pierre qui roule', 'tempête dans un verre d\'eau', 'montagne qui accouche',

  // ── Expressions idiomatiques ──────────────────────────────────────────────────
  'avoir le cafard', 'avoir la chair de poule', 'avoir le coeur sur la main',
  'avoir les pieds sur terre', 'avoir la tête dans les nuages',
  'casser les pieds', 'prendre son pied', 'tomber dans les pommes',
  'avoir un chat dans la gorge', 'poser un lapin', 'avoir le cafard',
  'couper les cheveux en quatre', 'brûler les étapes',
  'avoir le beurre et l\'argent du beurre', 'ne pas avoir la langue dans sa poche',
  'avoir d\'autres chats à fouetter', 'quand les poules auront des dents',
  'il ne faut pas vendre la peau de l\'ours',

  // ── Monuments & symboles ──────────────────────────────────────────────────────
  'drapeau', 'blason', 'armoiries', 'sceau', 'médaille', 'trophée', 'oscar',
  'croix rouge', 'croissant rouge', 'étoile de David', 'yin yang', 'ankh',
  'totem', 'talisman', 'amulette', 'gri-gri', 'attrape-rêve', 'mandala',
  'Yin Yang', 'om', 'trèfle à quatre feuilles', 'fer à cheval', 'patte de lapin',

  // ── Époque historique & culture ───────────────────────────────────────────────
  'chevalier médiéval', 'gladiateur romain', 'pharaon', 'viking',
  'samouraï', 'ninja', 'geisha', 'shogun', 'seigneur féodal',
  'conquistador', 'corsaire', 'flibustier', 'boucanier',
  'explorateur', 'pionnier', 'chercheur d\'or', 'trappeur',
  'cowboy', 'Amérindien', 'chef de tribu', 'chamane',
  'gladiateur', 'légionnaire romain', 'centurion', 'consul',
  'philosophe grec', 'oracle', 'augure', 'druide gaulois',

  // ── Couleurs & formes ─────────────────────────────────────────────────────────
  'cercle', 'carré', 'triangle', 'rectangle', 'losange', 'hexagone', 'octogone',
  'étoile', 'croix', 'spirale', 'vortex', 'infini', 'coeur', 'flèche',
  'cube', 'sphère', 'pyramide', 'cône', 'cylindre', 'tore', 'prisme',
  'arc', 'demi-lune', 'ellipse', 'ovale', 'pentagone', 'heptagone',
  'rouge', 'bleu', 'vert', 'jaune', 'orange', 'violet', 'rose',
  'blanc', 'noir', 'gris', 'marron', 'beige', 'turquoise', 'indigo',
  'arc-en-ciel', 'dégradé', 'camaïeu', 'contraste', 'harmonie de couleurs',

  // ── Saisons & fêtes ───────────────────────────────────────────────────────────
  'printemps', 'été', 'automne', 'hiver',
  'Noël', 'Halloween', 'Pâques', 'Saint-Valentin', 'fête des Mères', 'fête des Pères',
  'Nouvel An', 'carnaval', 'mardi gras', 'Ramadan', 'Aïd', 'Hanoukka', 'Diwali',
  'feu de joie', 'feu de camp', 'feu d\'artifice', 'défilé', 'procession',

  // ── Jeux & jouets ─────────────────────────────────────────────────────────────
  'dé à jouer', 'carte à jouer', 'jeu de cartes', 'poker', 'belote', 'tarot',
  'jeu d\'échecs', 'pion', 'roi', 'reine', 'fou', 'cavalier', 'tour',
  'Monopoly', 'Scrabble', 'Risk', 'Cluedo', 'Trivial Pursuit', 'Pictionary',
  '1, 2, 3 soleil', 'chat perché', 'cache-cache', 'loup', 'marelle',
  'billes', 'toupie', 'yoyo', 'pogs', 'tamagotchi', 'GameBoy',
  'hopscotch', 'saut à la corde', 'elastique', 'bonneteau',
  'dominos', 'Jenga', 'Mikado', 'jeu de l\'oie', 'backgammon', 'mancala',

  // ── Environnement & écologie ──────────────────────────────────────────────────
  'recyclage', 'compostage', 'déchetterie', 'pollution', 'marée noire',
  'sécheresse', 'inondation', 'incendie de forêt', 'fonte des glaces',
  'déforestation', 'désertification', 'érosion', 'glissement de terrain',
  'éolienne', 'panneau solaire', 'barrage hydraulique', 'marée motrice',
  'voiture électrique', 'vélo électrique', 'trottinette électrique',
  'tri sélectif', 'compost', 'lombricompost', 'jardinage urbain',
  'abeille', 'pollinisation', 'biodiversité', 'espèce en voie d\'extinction',
]

export function pickWords(n: number): string[] {
  const shuffled = [...WORDS].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, n)
}

export function wordToMask(word: string): string {
  return word.split('').map(c => (c === ' ' ? ' ' : '_')).join('')
}

export function revealLetter(mask: string, word: string): string {
  if (!mask || typeof mask !== 'string') return mask
  const chars = mask.split('')
  const hiddenIndexes: number[] = []
  for (let i = 0; i < chars.length; i++) {
    if (chars[i] === '_') hiddenIndexes.push(i)
  }
  if (hiddenIndexes.length === 0) return mask
  const idx = hiddenIndexes[Math.floor(Math.random() * hiddenIndexes.length)]!
  chars[idx] = word[idx]!
  return chars.join('')
}
