// 250 paires de mots proches pour Undercover
export const WORD_PAIRS: [string, string][] = [
  // Animaux
  ['Chat', 'Chien'],
  ['Lion', 'Tigre'],
  ['Dauphin', 'Requin'],
  ['Cheval', 'Âne'],
  ['Poule', 'Canard'],
  ['Mouton', 'Chèvre'],
  ['Cochon', 'Sanglier'],
  ['Loup', 'Renard'],
  ['Aigle', 'Vautour'],
  ['Grenouille', 'Crapaud'],
  ['Lapin', 'Lièvre'],
  ['Vache', 'Bison'],
  ['Crocodile', 'Alligator'],
  ['Pingouin', 'Manchot'],
  ['Hamster', 'Gerbille'],
  ['Perroquet', 'Perruche'],
  ['Hibou', 'Chouette'],
  ['Poulpe', 'Calmar'],
  ['Tortue', 'Lézard'],
  ['Gorille', 'Chimpanzé'],

  // Nourriture
  ['Pizza', 'Tarte flambée'],
  ['Hamburger', 'Hot-dog'],
  ['Sushi', 'Sashimi'],
  ['Crêpe', 'Gaufre'],
  ['Baguette', 'Ficelle'],
  ['Beurre', 'Margarine'],
  ['Yaourt', 'Fromage blanc'],
  ['Chocolat', 'Cacao'],
  ['Café', 'Thé'],
  ['Bière', 'Cidre'],
  ['Champagne', 'Mousseux'],
  ['Citron', 'Citron vert'],
  ['Tomate', 'Poivron'],
  ['Pomme', 'Poire'],
  ['Fraise', 'Framboise'],
  ['Cerise', 'Myrtille'],
  ['Pastèque', 'Melon'],
  ['Ananas', 'Mangue'],
  ['Noix', 'Noisette'],
  ['Crevette', 'Homard'],
  ['Saumon', 'Truite'],
  ['Thon', 'Espadon'],
  ['Poulet', 'Dinde'],
  ['Boeuf', 'Veau'],
  ['Jambon', 'Lardons'],
  ['Sel', 'Poivre'],
  ['Miel', 'Sirop d\'érable'],
  ['Ketchup', 'Moutarde'],
  ['Mayonnaise', 'Aïoli'],
  ['Chips', 'Crackers'],

  // Sports
  ['Football', 'Rugby'],
  ['Tennis', 'Badminton'],
  ['Natation', 'Plongée'],
  ['Ski', 'Snowboard'],
  ['Vélo', 'Trottinette'],
  ['Boxe', 'Karaté'],
  ['Judo', 'Jiu-jitsu'],
  ['Golf', 'Croquet'],
  ['Volleyball', 'Beach-volley'],
  ['Basketball', 'Handball'],
  ['Baseball', 'Cricket'],
  ['Surf', 'Wakeboard'],
  ['Escalade', 'Alpinisme'],
  ['Course à pied', 'Marche nordique'],
  ['Yoga', 'Pilates'],
  ['Gym', 'CrossFit'],
  ['Escrime', 'Tir à l\'arc'],
  ['Équitation', 'Polo'],
  ['Canoë', 'Kayak'],
  ['Patinage', 'Luge'],

  // Objets du quotidien
  ['Télévision', 'Moniteur'],
  ['Téléphone', 'Tablette'],
  ['Stylo', 'Crayon'],
  ['Cuillère', 'Fourchette'],
  ['Assiette', 'Bol'],
  ['Verre', 'Tasse'],
  ['Chaise', 'Tabouret'],
  ['Canapé', 'Fauteuil'],
  ['Lit', 'Matelas'],
  ['Oreiller', 'Coussin'],
  ['Miroir', 'Vitre'],
  ['Lampe', 'Bougie'],
  ['Clé', 'Cadenas'],
  ['Sac à dos', 'Cartable'],
  ['Parapluie', 'Imperméable'],
  ['Lunettes', 'Monocle'],
  ['Montre', 'Réveil'],
  ['Calculatrice', 'Abaque'],
  ['Livre', 'Magazine'],
  ['Journal', 'Agenda'],

  // Nature
  ['Montagne', 'Colline'],
  ['Mer', 'Lac'],
  ['Forêt', 'Jungle'],
  ['Désert', 'Savane'],
  ['Volcan', 'Geyser'],
  ['Fleuve', 'Rivière'],
  ['Cascade', 'Fontaine'],
  ['Plage', 'Côte'],
  ['Île', 'Presqu\'île'],
  ['Prairie', 'Champ'],
  ['Rose', 'Pivoine'],
  ['Tulipe', 'Jonquille'],
  ['Tournesol', 'Marguerite'],
  ['Chêne', 'Hêtre'],
  ['Pin', 'Sapin'],
  ['Bambou', 'Roseau'],
  ['Champignon', 'Truffe'],
  ['Mousse', 'Lichen'],
  ['Étoile', 'Planète'],
  ['Comète', 'Météorite'],

  // Lieux
  ['Château', 'Manoir'],
  ['Cathédrale', 'Église'],
  ['Mosquée', 'Temple'],
  ['Hôpital', 'Clinique'],
  ['École', 'Université'],
  ['Bibliothèque', 'Médiathèque'],
  ['Musée', 'Galerie'],
  ['Cinéma', 'Théâtre'],
  ['Restaurant', 'Brasserie'],
  ['Hôtel', 'Auberge'],
  ['Gare', 'Aéroport'],
  ['Supermarché', 'Épicerie'],
  ['Boulangerie', 'Pâtisserie'],
  ['Pharmacie', 'Laboratoire'],
  ['Stade', 'Gymnase'],
  ['Piscine', 'Jacuzzi'],
  ['Prison', 'Commissariat'],
  ['Ambassade', 'Consulat'],
  ['Phare', 'Tour'],
  ['Pont', 'Viaduc'],

  // Métiers
  ['Médecin', 'Chirurgien'],
  ['Avocat', 'Juge'],
  ['Policier', 'Gendarme'],
  ['Pompier', 'Secouriste'],
  ['Professeur', 'Formateur'],
  ['Architecte', 'Urbaniste'],
  ['Photographe', 'Caméraman'],
  ['Cuisinier', 'Pâtissier'],
  ['Coiffeur', 'Barbier'],
  ['Mécanicien', 'Électricien'],
  ['Pilote', 'Copilote'],
  ['Astronaute', 'Cosmonaute'],
  ['Plombier', 'Chauffagiste'],
  ['Jardinier', 'Paysagiste'],
  ['Comptable', 'Auditeur'],
  ['Journaliste', 'Reporter'],
  ['Acteur', 'Doublure'],
  ['Chanteur', 'Rappeur'],
  ['Danseur', 'Chorégraphe'],
  ['Écrivain', 'Poète'],

  // Transports
  ['Voiture', 'Camionnette'],
  ['Bus', 'Tramway'],
  ['Train', 'Métro'],
  ['Avion', 'Hélicoptère'],
  ['Bateau', 'Yacht'],
  ['Moto', 'Scooter'],
  ['Tracteur', 'Bulldozer'],
  ['Ambulance', 'Camion de pompiers'],
  ['Sous-marin', 'Bathyscaphe'],
  ['Fusée', 'Navette spatiale'],

  // Vêtements
  ['Manteau', 'Veste'],
  ['Robe', 'Jupe'],
  ['Pantalon', 'Jean'],
  ['Pull', 'Sweat'],
  ['Chemise', 'Chemisier'],
  ['Chaussures', 'Bottes'],
  ['Sandales', 'Tongs'],
  ['Chapeau', 'Casquette'],
  ['Écharpe', 'Foulard'],
  ['Gants', 'Mitaines'],

  // Technologie
  ['Ordinateur', 'Laptop'],
  ['Imprimante', 'Scanner'],
  ['Clé USB', 'Disque dur'],
  ['Casque', 'Oreillette'],
  ['Caméra', 'Webcam'],
  ['Robot', 'Drone'],
  ['Satellite', 'Antenne'],
  ['Batterie', 'Pile'],
  ['Chargeur', 'Câble'],
  ['Wifi', 'Bluetooth'],

  // Jeux & Loisirs
  ['Échecs', 'Dames'],
  ['Poker', 'Bridge'],
  ['Monopoly', 'Risk'],
  ['Puzzle', 'Casse-tête'],
  ['Peinture', 'Dessin'],
  ['Sculpture', 'Poterie'],
  ['Tricot', 'Crochet'],
  ['Jardinage', 'Bricolage'],
  ['Lecture', 'Écriture'],
  ['Randonnée', 'Camping'],

  // Musique
  ['Guitare', 'Basse'],
  ['Piano', 'Orgue'],
  ['Violon', 'Alto'],
  ['Trompette', 'Trombone'],
  ['Flûte', 'Clarinette'],
  ['Batterie', 'Percussion'],
  ['Microphone', 'Ampli'],
  ['DJ', 'Beatmaker'],
  ['Opéra', 'Comédie musicale'],
  ['Concert', 'Festival'],

  // Corps humain
  ['Bras', 'Jambe'],
  ['Main', 'Pied'],
  ['Oeil', 'Oreille'],
  ['Nez', 'Bouche'],
  ['Dent', 'Ongle'],
  ['Cheveux', 'Barbe'],
  ['Coeur', 'Poumon'],
  ['Cerveau', 'Moelle épinière'],
  ['Muscle', 'Tendon'],
  ['Os', 'Cartilage'],

  // Météo & Saisons
  ['Pluie', 'Grêle'],
  ['Neige', 'Givre'],
  ['Brouillard', 'Brume'],
  ['Orage', 'Tempête'],
  ['Arc-en-ciel', 'Aurore boréale'],
  ['Soleil', 'Lune'],
  ['Printemps', 'Été'],
  ['Automne', 'Hiver'],
  ['Vent', 'Bourrasque'],
  ['Tsunami', 'Inondation'],

  // Émotions & Concepts
  ['Amour', 'Amitié'],
  ['Joie', 'Bonheur'],
  ['Tristesse', 'Mélancolie'],
  ['Peur', 'Angoisse'],
  ['Colère', 'Frustration'],
  ['Surprise', 'Étonnement'],
  ['Jalousie', 'Envie'],
  ['Fierté', 'Vanité'],
  ['Courage', 'Audace'],
  ['Patience', 'Tolérance'],

  // Histoire & Culture
  ['Roi', 'Empereur'],
  ['Chevalier', 'Soldat'],
  ['Épée', 'Lance'],
  ['Bouclier', 'Armure'],
  ['Pyramide', 'Sphinx'],
  ['Gladiateur', 'Centurion'],
  ['Viking', 'Pirate'],
  ['Pharaon', 'Sultan'],
  ['Philosophe', 'Théologien'],
  ['Révolution', 'Révolte'],

  // Divers
  ['Magie', 'Illusion'],
  ['Rêve', 'Cauchemar'],
  ['Secret', 'Mystère'],
  ['Aventure', 'Exploration'],
  ['Trésor', 'Diamant'],
  ['Zombie', 'Vampire'],
  ['Fantôme', 'Esprit'],
  ['Alien', 'Robot'],
  ['Héros', 'Super-héros'],
  ['Monstre', 'Démon'],
]
